name: Omega Com
on: [push]
jobs:
  omega-com:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Install Dependencies
        run: npm install
      - name: Validate Lint
        run: npx eslint "src/**" 
      - name: Run Tests
        run: npm test